--[[

    ------01/10/2025------
    * Added the shop (MAKE SURE TO GO INTO `StarterPlayer/StarterPlayerScripts/UI/Shop` IN THE EXAMPLE PLACE TO GRAB WHAT YOU NEED FOR IT TO WORK)
    * Added reward notifications (e.g. when buying a character or getting a character from an achievement) (MAKE SURE TO GO INTO `StarterGui` AND `StarterPlayerScritps/UI/Shop` IN THE EXAMPLE PLACE TO GRAB WHAT YOU NEED FOR IT TO WORK)

    ------06/10/2025------
    * Added spectator & ragdoll collision group (MAKE SURE TO GO INTO `Collision Groups` IN `Window -> 3D -> Collision Groups` IN THE EXAMPLE PLACE TO GRAB WHAT YOU NEED FOR IT TO WORK)

    ------08/10/2025------
    * Added shift lock fixes and execution animations (MAKE SURE TO GO INTO `StarterPlayerScripts/PlayerModule/CameraModule` AND REPLACE YOUR `SmoothShiftLock` WITH THE ONE IN THE EXAMPLE PLACE CURRENTLY)
    * Rearranged SFX in character configs (check the diff)

    ------09/10/2025------
    * Added Round Player List (MAKE SURE TO GO INTO `StarterPlayer/StarterPlayerScripts/UI/RoundPlayerList` IN THE EXAMPLE PLACE TO GRAB WHAT YOU NEED FOR IT TO WORK)
    
    ------16/10/2025------
    * Refactored TerrorRadius to not be a util and be embedded to each character instead
    * Added TopbarPlus for the mod panel
]]

script:Destroy()